name: "JapanHorseRaceAnalytics"
version: "1.0.0"
config-version: 2
profile: JapanHorseRaceAnalytics
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
models:
  JapanHorseRaceAnalytics:
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    curated:
      +schema: curated
seeds:
  JapanHorseRaceAnalytics:
    +schema: seed
    # Make sure "code" columns are parsed as strings, not integers.
    # This workaround is really buggy. If it fails to parse a column as a string,
    # try changing 'text' to 'varchar' and re-running with --full-refresh.
    jrdb_racetrack_jma_station_mapping:
      +column_types:
        jrdb_racetrack_code: text
    jma_天気記号:
      +column_types:
        code: text
    jma_品質情報:
      +column_types:
        code: text
    jma_現象なし情報:
      +column_types:
        code: text
    天候コード:
      +column_types:
        code: text
    場コード:
      +column_types:
        code: text
    特記コード:
      +column_types:
        コード: text
    調教コースコード:
      +column_types:
        コード: text
    追い状態コード:
      +column_types:
        コード: text
    条件コード:
      +column_types:
        code: text
        group_code: text
    馬場状態コード:
      +column_types:
        code: text
    調教矢印コード:
      +column_types:
        code: text
    厩舎評価コード:
      +column_types:
        code: text
    蹄コード:
      +column_types:
        code: text
    重適性コード:
      +column_types:
        code: text
    クラスコード:
      +column_types:
        code: text
    印コード:
      +column_types:
        code: text
    展開記号コード:
      +column_types:
        code: text
    距離適性コード:
      +column_types:
        code: text
    馬記号コード:
      +column_types:
        code: text
    上昇度コード:
      +column_types:
        code: text
    休養理由分類コード:
      +column_types:
        code: text
    馬体コード:
      +column_types:
        code: text
    気配コード:
      +column_types:
        code: text
    毛色コード:
      +column_types:
        code: text
    系統コード:
      +column_types:
        コード: text
    脚質コード:
      +column_types:
        code: text
    馬具コード:
      +column_types:
        コード: text
    異常区分コード:
      +column_types:
        code: text
    競走種別コード:
      +column_types:
        code: text
    重量コード:
      +column_types:
        code: text
    グレードコード:
      +column_types:
        code: text
