name: "jhra"
version: "1.0.0"
config-version: 2
profile: jhra
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
models:
  jhra:
    +materialized: table
    +file_format: parquet
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    curated:
      +schema: curated
seeds:
  # Globally quote all seed columns
  # https://docs.getdbt.com/reference/resource-configs/quote_columns
  +quote_columns: true
  jhra:
    +schema: seed
    # Make sure "code" columns are parsed as strings, not integers.
    # This workaround is really buggy. If it fails to parse a column as a string,
    # try changing 'string' to 'varchar' and re-running with --full-refresh.
    jrdb_racetrack_jma_station_mapping:
      +column_types:
        jrdb_racetrack_code: string
    jma__weather_symbols:
      +column_types:
        code: string
    jma__quality_codes:
      +column_types:
        code: string
    jma__phenomenon_codes:
      +column_types:
        code: string
    jrdb__weather_codes:
      +column_types:
        code: string
    jrdb__racetrack_codes:
      +column_types:
        code: string
    jrdb__special_mention_codes:
      +column_types:
        code: string
    jrdb__training_course_codes:
      +column_types:
        code: string
    jrdb__workout_status_codes:
      +column_types:
        code: string
    jrdb__race_condition_codes:
      +column_types:
        code: string
        group_code: string
    jrdb__going_codes:
      +column_types:
        code: string
    jrdb__trainer_evaluation_codes:
      +column_types:
        code: string
    jrdb__stable_evaluation_codes:
      +column_types:
        code: string
    jrdb__paddock_observed_hoof_codes:
      +column_types:
        code: string
    jrdb__heavy_ground_aptitude_codes:
      +column_types:
        code: string
    jrdb__class_codes:
      +column_types:
        code: string
    jrdb__symbol_codes:
      +column_types:
        code: string
    jrdb__race_development_codes:
      +column_types:
        code: string
    jrdb__distance_aptitude_codes:
      +column_types:
        code: string
    jrdb__horse_symbol_codes:
      +column_types:
        code: string
    jrdb__improvement_codes:
      +column_types:
        code: string
    jrdb__rest_reason_codes:
      +column_types:
        code: string
    jrdb__horse_form_codes:
      +column_types:
        code: string
    jrdb__demeanor_codes:
      +column_types:
        code: string
    jrdb__hair_color_codes:
      +column_types:
        code: string
    jrdb__lineage_codes:
      +column_types:
        code: string
    jrdb__run_style_codes:
      +column_types:
        code: string
    jrdb__horse_owner_association_codes:
      description: |
        Codes for 馬主会コード.
        This is a copy of the seed file seeds/jrdb__racetrack_codes.csv with additional "unknown" values.
        See UKC schema for details.
      +column_types:
        code: string
    jrdb__horse_gear_codes:
      +column_types:
        code: string
    jrdb__anomaly_codes:
      +column_types:
        code: string
    jrdb__race_category_codes:
      +column_types:
        code: string
    jrdb__weight_condition_codes:
      +column_types:
        code: string
    jrdb__grade_codes:
      +column_types:
        code: string
