services:
  # psql -U admin -h localhost -p 5432 -d jrdb
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/:/var/lib/postgresql/data
      - ./docker/postgres-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d jrdb || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # http://localhost:5050
  # https://hub.docker.com/r/dpage/pgadmin4
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:80/login || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  thriftserver:
    build:
      context: ./docker
      dockerfile: spark.Dockerfile
    ports:
      - "10000:10000"
      - "4040:4040"
    depends_on:
      - postgres
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server
    volumes:
      - ./.spark-warehouse/:/spark-warehouse/
      - ./docker/hive-site.xml:/usr/spark/conf/hive-site.xml
      - ./docker/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
    environment:
      - WAIT_FOR=postgres:5432

  # dbt-hive-metastore:
  #   image: postgres:9-alpine
  #   volumes:
  #     - ./.hive-metastore/:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=dbt
  #     - POSTGRES_PASSWORD=dbt
  #     - POSTGRES_DB=metastore

volumes:
  pgadmin:
