JapanHorseRaceAnalytics:
  # default target
  target: local

  outputs:
    local:
      type: postgres
      method: jdbc
      user: admin
      password: admin
      # This is the target schema name.
      # When combined with custom schema name (e.g. in dbt_profile.yml)
      # the resulting schema name is "jrdb_<custom_schema_name>".
      # https://docs.getdbt.com/docs/build/custom-schemas#understanding-custom-schemas
      schema: jrdb
      database: jrdb
      host: localhost
      port: 5432

    local_spark:
      type: spark
      method: thrift
      schema: jhra
      host: localhost
      port: 10000
      threads: 4