jhra:
  target: local
  outputs:
    local:
      type: spark
      method: thrift
      host: thriftserver
      port: 10000
      user: admin
      # In dbt_project.yml we set custom schema names like "staging", "intermediate", "curated", and "seed".
      # So the resulting schema names will be "jhra_staging", "jhra_intermediate", "jhra_curated", and "jhra_seed".
      # https://docs.getdbt.com/docs/build/custom-schemas#understanding-custom-schemas
      schema: jhra
      connect_retries: 5
      connect_timeout: 15
      retry_all: true
      threads: 8
