jhra:
  target: local
  outputs:
    local:
      type: spark
      method: thrift
      host: thriftserver
      port: 10000
      user: admin
      # This is the target schema name.
      # When combined with custom schema name (e.g. in dbt_profile.yml)
      # the resulting schema name is "jhra_<custom_schema_name>".
      # https://docs.getdbt.com/docs/build/custom-schemas#understanding-custom-schemas
      schema: jrdb
      connect_retries: 5
      connect_timeout: 15
      retry_all: true
      threads: 4
