JapanHorseRaceAnalytics:
  target: local

  outputs:
    # old target using postgres
    # local:
    #   type: postgres
    #   method: jdbc
    #   user: admin
    #   password: admin
    #   schema: jrdb
    #   database: jrdb
    #   host: localhost
    #   port: 5432

    local:
      type: spark
      method: thrift
      # This is the target schema name.
      # When combined with custom schema name (e.g. in dbt_profile.yml)
      # the resulting schema name is "jhra_<custom_schema_name>".
      # https://docs.getdbt.com/docs/build/custom-schemas#understanding-custom-schemas
      schema: jhra
      host: localhost
      port: 10000
      threads: 4
