-- Schemas for JRDB
CREATE SCHEMA IF NOT EXISTS jrdb_raw AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS jrdb_intermediate AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS jrdb_curated AUTHORIZATION admin;
-- MLFlow DB
CREATE DATABASE mlflow OWNER admin;
