version: 2
seeds:
  - name: jrdb_racetrack_jma_station_mapping
    columns:
      - name: jrdb_racetrack_code
        tests:
          - unique
          - not_null
      - name: jrdb_racetrack_name
        tests:
          - not_null
      - name: jma_station_name
        tests:
          - not_null
  - name: jma_品質情報
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: description
        tests:
          - not_null
  - name: jma_天気記号
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: weather_symbol
        tests:
          - not_null
      - name: weather
        tests:
          - not_null
      - name: visual_observation
        tests:
          - not_null
      - name: mechanical_observation
  - name: jma_現象なし情報
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: description
        tests:
          - not_null
  - name: 天候コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: weather_condition
        tests:
          - not_null
  - name: 場コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 特記コード
    columns:
      - name: コード
        tests:
          - unique
          - not_null
      - name: 短縮
        tests:
          - not_null
      - name: 内容
        tests:
          - not_null
  - name: 調教コースコード
    columns:
      - name: コード
        tests:
          - unique
          - not_null
      - name: 調教コース
        tests:
          - not_null
      - name: 調教コース短縮
        tests:
          - not_null
  - name: 追い状態コード
    columns:
      - name: コード
        tests:
          - unique
          - not_null
      - name: 追い状態名
        tests:
          - not_null
  - name: 条件コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: group_code
        tests:
          - not_null
      - name: group_name
        tests:
          - not_null
      - name: old_code_name
  - name: 馬場状態コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 調教矢印コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 厩舎評価コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 蹄コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 重適性コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: クラスコード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 印コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 展開記号コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: description
        tests:
          - not_null
  - name: 距離適性コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 馬記号コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: horse_symbol_code
  - name: 上昇度コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: description
        tests:
          - not_null
  - name: 休養理由分類コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: rest_reason
        tests:
          - not_null
  - name: 馬体コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 気配コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: description
  - name: 毛色コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 系統コード
    columns:
      - name: コード
        tests:
          - unique
          - not_null
      - name: 小系統名
        tests:
          - not_null
      - name: 大系統名
        tests:
          - not_null
  - name: 脚質コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 馬具コード
    columns:
      - name: コード
        tests:
          - unique
          - not_null
      - name: 短縮
        tests:
          - not_null
      - name: 内容
        tests:
          - not_null
      - name: 馬具種別
        tests:
          - not_null
  - name: 異常区分コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 競走種別コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: 重量コード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
  - name: グレードコード
    columns:
      - name: code
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
